name: shubhtoursandtravels
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  counter: ^0.2.2
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  animated_text_kit: ^4.2.2
  country_code_picker: ^3.0.0
  cloud_firestore: ^4.8.4
  shared_preferences: ^2.2.0
  firebase_storage: ^11.2.6
  file_picker: ^5.5.0
  syncfusion_flutter_pdfviewer: ^22.2.12
  # stripe_payment: ^1.1.4  # Replace with the latest version
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:
    - family: Northwell
      fonts:
        - asset: fonts/Northwell.ttf
    - family: MPIDeco
      fonts:
        - asset: fonts/MPIDeco.ttf
